# Generated by Django 4.0.3 on 2022-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_color_image_tag_alter_image_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tag',
            field=models.ManyToManyField(blank=True, to='banner.tag'),
        ),
    ]
