# Generated by Django 4.0.3 on 2022-03-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_alter_image_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banner.color'),
        ),
    ]
