# Generated by Django 4.0.3 on 2022-03-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='color code'),
        ),
    ]
